# Virtual History Website Configuration

remote_theme: Phlow/feeling-responsive@gh-pages
plugins:
  - jekyll-feed
  - jekyll-remote-theme
urlimg: "https://virtualhistory.github.io/Website/images/"

markdown: kramdown

# For feeling-responsive
title: "Virtual History Title"
slogan: "Virtual History Slogan"
description: "Impressum:\nVirtual History\nFilmuniversit√§t Babelsberg KONRAD WOLF\nMarlene-Dietrich-Allee 11\n(Studios Ahornstrasse 18)\n14482 Babelsberg\nfon: 0331 - 6202 - 164\nb.hetenyi(at)filmuniversitaet.de"
logo: "logo.png"
favicon-32x32: "favicon-32x32.png"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
